# Generated by Django 5.0.8 on 2024-08-08 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0004_remove_astronomyshow_show_theme_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ticket",
            name="unique_ticket_seat_show_session",
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("seat", "show_session")},
        ),
    ]
