# Generated by Django 5.0.8 on 2024-08-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0005_remove_ticket_unique_ticket_seat_show_session_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="showtheme",
            name="name",
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
