# Generated by Django 5.0.8 on 2024-08-09 19:20

import planetarium.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0006_alter_showtheme_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="astronomyshow",
            name="image",
            field=models.ImageField(
                null=True, upload_to=planetarium.models.astronomy_show_image_path
            ),
        ),
    ]
