# Generated by Django 5.0.8 on 2024-08-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0007_astronomyshow_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="astronomyshow",
            name="show_theme",
            field=models.ManyToManyField(
                blank=True, related_name="show_themes", to="planetarium.showtheme"
            ),
        ),
    ]
